modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="easy_economy"
version="1.0.0"
displayName="Easy Economy"
credits="The_WereF0X"
displayURL="https://discord.gg/8gWbTqKuhF"
updateJSONURL="https://discord.gg/8gWbTqKuhF"
logoFile="logo.png"
authors="The_WereF0X"
description="Introduces a simple economy addon in your game. To sell items, do /sell. To buy items, do /shop. To see your balance, do /balance. Admins can do /balance:set (player) (amount) to set a player(s) balance to a  certain amount."

[[dependencies.easy_economy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




